In [ ]:
import pandas as pd
#pandas의 장점: 보기 쉽다. excel처럼.
#visual basic의 기능과 python의 쉬운 문법 + excel의 가독성을 가져온 라이브러리.

In [ ]:
#tap separated values
#df: data frame class
df = pd.read_csv('data/gapminder.tsv',sep='\t')

In [20]:
#pandas에서는 object=string이다 라고 이해하면 된다.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [ ]:
df['country']

#df: row,column 구조.
#series : vector 길이가 1인 행 또는 열.

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: str

In [ ]:
df[['country','continent','year']]

#column 3개인 series = df
#2줄 이상의 series는 df로 자동 변경된다.

          country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

데이터 분석 과정

전처리 - 통계 - 그래프(시각화)

In [ ]:
df.loc[-1]
#loc는  -1이라는 키가 존재하지 않는다.


#index=country, value=

KeyError: -1

In [ ]:
df.loc[0:3]
#slicing이 아니라, loc[A:B] A부터 B까지 인덱스 값

df.loc[3:0]
#인덱스 3부터 내려가서 0을 찾기.
#하지만 3아래에 0이 없어서, 검색된 값이 없었다.
#마지막 값을 반드시 찾아야만 값을 return하는 구나.

#iloc와 loc의 사용 구분을 잘 숙지하는것이 중요할듯.

Empty DataFrame
Columns: [country, continent, year, lifeExp, pop, gdpPercap]
Index: []

In [65]:
df.loc[[0,1,10]]

        country continent  year  lifeExp       pop   gdpPercap
0   Afghanistan      Asia  1952   28.801   8425333  779.445314
1   Afghanistan      Asia  1957   30.332   9240934  820.853030
10  Afghanistan      Asia  2002   42.129  25268405  726.734055

KeyError: "None of ['index'] are in the columns"

In [ ]:
df.iloc[0].to_frame()
df.iloc[[0,1,2]]

#loc를 df형식으로 추출하기.

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [ ]:
#row,col.
df.loc[0,'continent']

df.iloc[0,1]

#값으로 column index 찾기
list(df.columns).index('continent')

#0~4번 행에서 1,5번 column만 선택.
df.iloc[0:5, [1,5]]

  continent   gdpPercap
0      Asia  779.445314
1      Asia  820.853030
2      Asia  853.100710
3      Asia  836.197138
4      Asia  739.981106

# 데이터 생성하기

In [ ]:
scientists = pd.DataFrame({
'Name':'RosalineFranklin',
'Occupation':'Chemist'
},
index=[1,2])
scientists

#기본적으로 [[]] nested 형태로 쓰거나,->비추
#아니면 index를 지정해야함.->비추 방식
#column만 만들고 이후 넣는 방식 사용.

               Name Occupation
1  RosalineFranklin    Chemist
2  RosalineFranklin    Chemist

In [ ]:
Scientists = pd.DataFrame(
    data={'Occupation':['Chemist','Statistician'],
    'Born':['1920-07-25','1876-06-13'],
    'Died':['1958-04-16','1937-10-16'],
    'Age':[37,61]},
    index=['RosalineFranklin','WilliamGosset'],
    columns=['Occupation','Born','Age','Died'])
scientists

               Name Occupation
1  RosalineFranklin    Chemist
2  RosalineFranklin    Chemist

In [ ]:

#가장 권장하는 방법
test=pd.DataFrame(columns=['a','b','c'])
test.loc[0]=['a','b','c']

#iloc는 리스트랑 비슷하기 때문에, 기존에 있는 값을
#수정,조회 가능,
# insert나 append가 없음.(추가 불가.)
#꿀팁: 인덱스와 함께 새 값 추가하고 싶으면 이렇게 반복
test.loc[len(test)]=['김','이','박']
test.loc[len(test)]=['김',None,'박']

# len(test) == test.shape[0]

a    0
b    1
c    0
dtype: int64

In [142]:
df.values

array([['Afghanistan', 'Asia', 1952, 28.801, 8425333, 779.4453145],
       ['Afghanistan', 'Asia', 1957, 30.332, 9240934, 820.8530296],
       ['Afghanistan', 'Asia', 1962, 31.997, 10267083, 853.10071],
       ...,
       ['Zimbabwe', 'Africa', 1997, 46.809, 11404948, 792.4499603],
       ['Zimbabwe', 'Africa', 2002, 39.989, 11926563, 672.0386227],
       ['Zimbabwe', 'Africa', 2007, 43.487, 12311143, 469.7092981]],
      shape=(1704, 6), dtype=object)

numpy는 pandas의 조상이다.
-> array안의 모든 값들이 숫자로 통일된다.
-> string -> int -> string 과정이 까다롭다.

그래서 pandas를 사용한다.

In [151]:
scientists=pd.read_csv('data/scientists.csv')
age=scientists['Age']
scientists


scientists.isin(['Chemist',61,'1820-05-12'])

    Name   Born   Died    Age  Occupation
0  False  False  False  False        True
1  False  False  False   True       False
2  False   True  False  False       False
3  False  False  False  False        True
4  False  False  False  False       False
5  False  False  False  False       False
6  False  False  False  False       False
7  False  False  False  False       False

In [161]:
test.isnull().sum()
#sum은 같은 값을 모두더한다.
scientists.isin([37,90]).sum()
#null -> true
# true + false =true이므로, true가 1개 이상이면 sum했을때 1이된다.
# null은 원래 sum 통계 연산에 포함되지 않으므로,
#is null이 1로 바꿔주는 역할을 한다.

Name          0
Born          0
Died          0
Age           2
Occupation    0
dtype: int64

In [163]:
scientists.count()
scientists.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   Born        8 non-null      str
 2   Died        8 non-null      str
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      str
dtypes: int64(1), str(4)
memory usage: 452.0 bytes

In [180]:
job=scientists['Occupation']
#count대신 value counts를 쓰자.
job.value_counts()

df['continent'].unique()
df['year'].max()

scientists.dtypes

Name            str
Born            str
Died            str
Age           int64
Occupation      str
dtype: object

In [ ]:
df.iloc[0]
df.columns(0)
#행의 경우, 여러 타입이 존재한다.
#모든 데이터 타입을 포함할 수 있는 타입은 string이고.
#-> 그래서 row를 가져오면 기본적으로 문자로 되니까.
#

TypeError: 'Index' object is not callable

In [ ]:

df.describe()

#데이터 통계 값을 한 눈에 볼 수 있게 해 준다.

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [264]:
random = df.sample(frac=1)
#표본: 랜덤 sample을 뽑는다.
#frac=1일 경우 모든 데이터 순서가 랜덤하게 섞인다.

#빅데이터분석: 전수 조사(샘플안씀)
#통계분석: 표본 대상 조사.

scientists.sort_values('Name',ascending=True)

                   Name        Born        Died  Age          Occupation
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
5             John Snow  1813-03-15  1858-06-16   45           Physician
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician

In [265]:
ages=scientists['Age']
ages.to_frame()

   Age
0   40
1   61
2   90
3   66
4   56
5   45
6   41
7   77

In [ ]:
ages +pd.Series([1,3,7],index=['1','2','3'])

#초보자는 index 수정 비추...
rev_ages=ages.sort_index(ascending=False)

ages= ages+rev_ages
ages

#실제 데이터는 섞여있든, index끼리 계산이 되기 때문에
#인덱스의 순서는 크게 중요하지 않다.
#그냥 보기 편하라고 씀.

0    160
1    244
2    360
3    264
4    224
5    180
6    164
7    308
Name: Age, dtype: int64

In [ ]:
#boolean indexing
#condition으로도 indexing이 가능하다.
#true인 '행'의 인덱스만 추출한다.
#조건을 만족하는 '행'만 가져와라.

scientists[scientists['Age']>scientists['Age'].mean()]

pandas.Series

전처리= 내가 원하는 조건에 맞는 데이터를 검색하는 것.

In [305]:
df

     country continent  year  lifeExp       pop   gdpPercap
0      Korea      Asia  1952   28.801   8425333  779.445314
1      Korea      Asia  1957   30.332   9240934  820.853030
2      Korea      Asia  1962   31.997  10267083  853.100710
3      Korea      Asia  1967   34.020  11537966  836.197138
4      Korea      Asia  1972   36.088  13079460  739.981106
...      ...       ...   ...      ...       ...         ...
1699   Korea    Africa  1987   62.351   9216418  706.157306
1700   Korea    Africa  1992   60.377  10704340  693.420786
1701   Korea    Africa  1997   46.809  11404948  792.449960
1702   Korea    Africa  2002   39.989  11926563  672.038623
1703   Korea    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [309]:
df[ df['country']== 'Korea' ]

     country continent  year  lifeExp       pop   gdpPercap
0      Korea      Asia  1952   28.801   8425333  779.445314
1      Korea      Asia  1957   30.332   9240934  820.853030
2      Korea      Asia  1962   31.997  10267083  853.100710
3      Korea      Asia  1967   34.020  11537966  836.197138
4      Korea      Asia  1972   36.088  13079460  739.981106
...      ...       ...   ...      ...       ...         ...
1699   Korea    Africa  1987   62.351   9216418  706.157306
1700   Korea    Africa  1992   60.377  10704340  693.420786
1701   Korea    Africa  1997   46.809  11404948  792.449960
1702   Korea    Africa  2002   39.989  11926563  672.038623
1703   Korea    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [318]:
print(scientists)

scientists['Born'].astype('datetime64[ns]')

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[ns]

In [ ]:
#대부분 함수들은 기존 값을 변경시키지 않고 
# 새로운 df나 series를 생성한 결과를 return한다. 
# 아마 다들 조회만 하고 기존 데이터를 수정하지 않길 원하는듯.

0    1958-04-16
1    1937-10-16
2    1910-08-13
3    1934-07-04
4    1964-04-14
5    1858-06-16
6    1954-06-07
7    1855-02-23
Name: Died, dtype: str

In [324]:
pd.to_datetime(scientists['Died'],format='%Y-%m-%d')

0   1958-04-16
1   1937-10-16
2   1910-08-13
3   1934-07-04
4   1964-04-14
5   1858-06-16
6   1954-06-07
7   1855-02-23
Name: Died, dtype: datetime64[us]

In [ ]:
scientists['lived']=scientists['Died']-scientists['Born']
#scientists['test']=pd.Series[1,100]

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
scientists.drop(3,axis=0)

#이렇게 해도 기존 df의 값이 바뀌지 않는다고.?
#assign 하지 않으면 절대 바뀌지 않는듯

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [350]:
#save
scientists.to_csv('data/scientists')

In [351]:
#pd.read ... 데이터를 읽는 함수들.

#pandas에서 불러오는 방법만 알면 어떤 데이터든 import 가능

pd.read_csv('data/scientists')

,Unnamed: 0,Name,Born,Died,Age,Occupation
0,0,Rosaline Franklin,1920-07-25,1958-04-16,40,Chemist
1,1,William Gosset,1876-06-13,1937-10-16,61,Statistician
2,2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse
3,3,Marie Curie,1867-11-07,1934-07-04,66,Chemist
4,4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist
5,5,John Snow,1813-03-15,1858-06-16,45,Physician
6,6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist
7,7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician

index는 저장시 0,1,2 .. 데이터로 저장이 된다.
왜냐면 저장할 때 인덱스인지 값인지 알 방법이 없기 때문이다.

In [365]:

not_indexed=scientists.to_csv('data/scientists_notIndexed.csv',index=False)
not_indexed

In [367]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\samsung\.venv\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pymysql
conn = pymysql.connect(
            host='121.152.203.186', user='test', password='1234',
            database='python_db',charset='utf8', port=33060) # 데이터베이스 접속

C:\Users\samsung\AppData\Local\Temp\ipykernel_23924\4003190208.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  emp=pd.read_sql('select * from emp',conn)
C:\Users\samsung\AppData\Local\Temp\ipykernel_23924\4003190208.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dept=pd.read_sql('select * from dept',conn)

In [375]:
emp=pd.read_sql('select * from emp',conn)
dept=pd.read_sql('select * from dept',conn)
conn.close()

C:\Users\samsung\AppData\Local\Temp\ipykernel_23924\3939723144.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  emp=pd.read_sql('select * from emp',conn)
C:\Users\samsung\AppData\Local\Temp\ipykernel_23924\3939723144.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dept=pd.read_sql('select * from dept',conn)

pandas의 경우 db 회사에 맞춰 지원/유지보수가 어려웠음.

-> sqlAlchemy만 공식지원.

->모든 DB 호환가능한 라이브러리.

In [376]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\samsung\.venv\lib\site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 20.3 MB/s eta 0:00:00
Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl (247 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.5.4 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [387]:
import sqlalchemy as sql

engine=sql.create_engine('mysql+pymysql://test:1234@121.152.203.186:33060/python_db')

emp=pd.read_sql('select * from emp',engine)

emp.to_sql('armani',engine,if_exists='replace',index=False)
#sql을 많이 쓸 이유가 없다.
#pandas에서 table manipulation

14

In [ ]:
#데이터 저장시 최대한 padding이 적도록.

emp['empno'].astype('Int16')

0     7369
1     7499
2     7521
3     7566
4     7654
5     7698
6     7782
7     7788
8     7839
9     7844
10    7876
11    7900
12    7902
13    7934
Name: empno, dtype: Int16

In [389]:
df1=pd.read_csv('data/concat_1.csv')
df2=pd.read_csv('data/concat_2.csv')
df3=pd.read_csv('data/concat_3.csv')

In [394]:
combined=pd.concat([df1,df2,df3])
combined

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [399]:
combined.loc[3]

     A    B    C    D
3   a3   b3   c3   d3
3   a7   b7   c7   d7
3  a11  b11  c11  d11

In [395]:
combined.info()

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     str
 1   B       12 non-null     str
 2   C       12 non-null     str
 3   D       12 non-null     str
dtypes: str(4)
memory usage: 480.0 bytes

In [404]:
col_concat=pd.concat([df1,df2,df3],axis=1)

col_concat

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [423]:
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['E', 'F', 'G', 'H']
df3.columns = ['A', 'C', 'F', 'H']

In [426]:
df3.columns

Index(['A', 'C', 'F', 'H'], dtype='str')

In [ ]:
df3.colums=df1.columns
pd.concat([df1,df3],join='left inner')

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
0   a8   b8
1   a9   b9
2  a10  b10
3  a11  b11

In [429]:
person = pd.read_csv('data/survey_person.csv')
site = pd.read_csv('data/survey_site.csv')
visited = pd.read_csv('data/survey_visited.csv')
survey = pd.read_csv('data/survey_survey.csv')

In [ ]:
sv.merge

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

Numpy 시작.

In [452]:
import numpy as np
type(np.array(1))

#특정 항이 null인 row 찾기.

emp[  emp['comm'].notnull()]

   empno   ename       job     mgr    hiredate     sal    comm  deptno
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0      30

In [453]:
ebola = pd.read_csv('data/country_timeseries.csv')
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [460]:
ebola.tail()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
117,3/27/2014,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
118,3/26/2014,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,3/25/2014,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,3/24/2014,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,3/22/2014,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [463]:
ebola.fillna(np.nan)

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
118,3/26/2014,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,3/25/2014,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,3/24/2014,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,3/22/2014,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [470]:
ebola.ffill()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2769.0,8157.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,66.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
118,3/26/2014,4,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,62.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
119,3/25/2014,3,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,60.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
120,3/24/2014,2,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,59.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
121,3/22/2014,0,49.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,29.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0